
# 开始使用本地静态资源
post_asset_folder: true
# 小图标
favicon: https://img.fansqz.com/img/favicon.ico
#导航页
menu:
  首页: / || fas fa-home
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

#头像
avatar:
  img: https://img.fansqz.com/img/head.jpg
  effect: false
#社交图标
social:
  fab fa-github: https://github.com/leaf-dawn || Github
  fas fa-envelope: 2958556459@qq.com || Email
  
#图标
index_img: https://img.fansqz.com/img/topimg.jpg
#顶部图片下的文字
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  # loop (滚动打字打字)
  loop: false
  # source 调用第三方服务
  source: false
  # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
  sub:
   - 种一棵树最好的时间是十年前，其次是现在


#分类图片
category_per_img:
  操作系统: https://img.fansqz.com/oss/blog/img1.jpg
  java容器源码: https://img.fansqz.com/oss/blog/img2.jpg
  计算机网络: https://img.fansqz.com/oss/blog/img3.jpg

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover: 

aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: left # left or right
  display:
    archive: true
    tag: true
    category: true
  #作者页
  card_author:
    enable: true
    description:
    button:
      enable: true
      text: Github
      link: https://github.com/leaf-dawn
  #公告
  card_announcement:
      enable: true
      content: This is my Blog


# 搜索相关配置
local_search:
  enable: true